version: '3.9'
services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    pull_policy: always 
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/ddauction_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    pull_policy: always 
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"